### ISSUE TITLE
make_unique_ccds_transcripts.R error

### ISSUE THREAD

**Issue by madaojjc** [rasilab/adarnell_2018#1]
Hi, when I use your Rscript make_unique_ccds_transcripts.R, I met error like this: 

> # subset transcripts that have ccds and are identified by APPRIS
> # for each gene pick lowest number ccds
> # for each ccds pick lowest number transcript
> ccdstx <- (
+   annotationsdf
+   %>% filter(!is.na(ccdsid))
+   %>% filter(str_detect(tag, "appris_principal"))
+   %>% filter(gene_type == 'protein_coding')
+   %>% filter(type == 'transcript')
+   %>% mutate(ccdsnum = as.numeric(substring(ccdsid, 5)))
+   %>% mutate(txnum = as.numeric(substring(ID, 5)))
+   %>% group_by(gene_id)
+   %>% filter(ccdsnum == min(ccdsnum))
+   %>% filter(txnum == min(txnum))
+ )
Warning messages:
1: In stri_detect_regex(string, pattern, negate = negate, opts_regex = opts(pattern)) :
  argument is not an atomic vector; coercing
2: 强制改变过程中产生了NA 

and 

> ######################################################################################################
> # extract remaining non-canonical annotations and write them to a file
> nonccds <- annotations[!(annotations$transcript_id %in% ccdstx$transcript_id)
+                        & annotations$type == 'exon' & annotations$gene_type == 'protein_coding' &
+                          !str_detect(annotations$tag, "PAR")
+                        ]
Error in as.vector(x, mode) : 
  coercing an AtomicList object to an atomic vector is supported only for
  objects with top-level elements of length <= 1

Thank you for your reply!

**Comment by rasi** [comment]
You probably need to download the right annotations file in this line:
https://github.com/rasilab/adarnell_2018/blob/master/scripts/make_unique_ccds_transcripts.R#L10
from here:
https://www.gencodegenes.org/human/release_24.html

**Comment by madaojjc** [comment]
> You probably need to download the right annotations file in this line:
> https://github.com/rasilab/adarnell_2018/blob/master/scripts/make_unique_ccds_transcripts.R#L10
> from here:
> https://www.gencodegenes.org/human/release_24.html

THANKS!
I downloaded the annotations file from the https://www.gencodegenes.org/human/release_24.html, But it still doesn't work... 


> ######################################################################################################
> # extract remaining non-canonical annotations and write them to a file
> nonccds <- annotations[!(annotations$transcript_id %in% ccdstx$transcript_id)
+                        & annotations$type == 'exon' & annotations$gene_type == 'protein_coding' &
+                          !str_detect(annotations$tag, "PAR")
+                        ]
Error in as.vector(x, mode) : 
  coercing an AtomicList object to an atomic vector is supported only for
  objects with top-level elements of length <= 1

**Comment by rasi** [comment]
Sorry, I am not sure what is going on since it is working on my end. Might be useful to ask in Bioconductor or Tidyverse help mailing lists since we are just using their packages for this code.

**Comment by madaojjc** [comment]
> Sorry, I am not sure what is going on since it is working on my end. Might be useful to ask in Bioconductor or Tidyverse help mailing lists since we are just using their packages for this code.

All right, I think it may be due to the different versions of the package....
